<!-- My Calendar Section -->
<div id="my-calendar-section" class="hidden">
    <div class="mb-3">
        <div class="flex items-center gap-2 mb-1">
            <div class="w-7 h-7 bg-gradient-to-br from-cyan-400 to-cyan-600 rounded-md flex items-center justify-center shadow-lg shadow-cyan-500/50">
                <i class="fas fa-calendar-days text-white text-xs"></i>
            </div>
            <div>
                <h2 class="text-sm font-bold text-white">My Health Calendar</h2>
                <p class="text-white/60 text-[10px]">View all your health events in one place</p>
            </div>
        </div>
    </div>

    <!-- Calendar Legend -->
    <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-lg p-2 mb-3">
        <div class="flex flex-wrap items-center gap-2">
            <span class="text-white/70 text-[10px] font-semibold">Events:</span>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-cyan-400"></span>
                <span class="text-white/70 text-[9px]">Appointments</span>
            </div>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-vital-orange"></span>
                <span class="text-white/70 text-[9px]">Med Refills</span>
            </div>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-purple-400"></span>
                <span class="text-white/70 text-[9px]">Lab Tests</span>
            </div>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-green-400"></span>
                <span class="text-white/70 text-[9px]">Follow-ups</span>
            </div>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-amber-400"></span>
                <span class="text-white/70 text-[9px]">Vaccinations</span>
            </div>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-pink-400"></span>
                <span class="text-white/70 text-[9px]">Insurance</span>
            </div>
            <div class="flex items-center gap-0.5">
                <span class="w-1.5 h-1.5 rounded-full bg-red-400"></span>
                <span class="text-white/70 text-[9px]">Bills Due</span>
            </div>
        </div>
    </div>

    <!-- Calendar Container -->
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-3">
        <!-- Main Calendar -->
        <div class="xl:col-span-2">
            <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-lg p-3 hover:border-cyan-400/30 transition-all duration-300">
                <!-- Calendar Header -->
                <div class="flex items-center justify-between mb-2">
                    <button onclick="changeMonth(-1)" class="w-6 h-6 flex items-center justify-center rounded bg-white/10 hover:bg-cyan-400/20 text-white hover:text-cyan-400 transition-all duration-300">
                        <i class="fas fa-chevron-left text-[10px]"></i>
                    </button>
                    <h3 id="calendarMonthYear" class="text-xs font-bold text-white"></h3>
                    <button onclick="changeMonth(1)" class="w-6 h-6 flex items-center justify-center rounded bg-white/10 hover:bg-cyan-400/20 text-white hover:text-cyan-400 transition-all duration-300">
                        <i class="fas fa-chevron-right text-[10px]"></i>
                    </button>
                </div>

                <!-- Calendar Grid -->
                <div class="grid grid-cols-7 gap-0.5 mb-1">
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Sun</div>
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Mon</div>
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Tue</div>
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Wed</div>
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Thu</div>
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Fri</div>
                    <div class="text-center text-white/50 text-[10px] font-semibold py-0.5">Sat</div>
                </div>

                <div id="calendarGrid" class="grid grid-cols-7 gap-0.5">
                    <!-- Calendar days will be generated by JavaScript -->
                </div>

                <!-- Today Button -->
                <div class="mt-2 text-center">
                    <button onclick="goToToday()" class="px-3 py-1 bg-gradient-to-r from-cyan-400 to-cyan-600 text-white text-[10px] font-semibold rounded hover:shadow-lg hover:shadow-cyan-500/50 transition-all duration-300 hover:scale-105">
                        <i class="fas fa-calendar-day mr-1"></i>Today
                    </button>
                </div>
            </div>
        </div>

        <!-- Events Sidebar -->
        <div class="xl:col-span-1">
            <!-- Selected Date Events -->
            <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-lg p-3 hover:border-cyan-400/30 transition-all duration-300 mb-3">
                <h3 id="selectedDateTitle" class="text-xs font-bold text-white mb-2 flex items-center gap-1">
                    <i class="fas fa-calendar-check text-cyan-400 text-[10px]"></i>
                    <span>Today's Events</span>
                </h3>
                <div id="selectedDateEvents" class="space-y-1.5">
                    <p class="text-white/50 text-[10px] text-center py-2">Select a date to view events</p>
                </div>
            </div>

            <!-- Upcoming Events -->
            <div class="bg-white/5 backdrop-blur-xl border border-white/10 rounded-lg p-3 hover:border-cyan-400/30 transition-all duration-300">
                <h3 class="text-xs font-bold text-white mb-2 flex items-center gap-1">
                    <i class="fas fa-clock text-vital-orange text-[10px]"></i>
                    Upcoming Events
                </h3>
                <div id="upcomingEventsList" class="space-y-1.5 max-h-48 overflow-y-auto scrollbar-thin scrollbar-thumb-cyan-500/20">
                    <!-- Upcoming events will be loaded here -->
                </div>
            </div>
        </div>
    </div>

    <!-- Month Overview Stats -->
    <div class="grid grid-cols-4 md:grid-cols-7 gap-1.5 mt-3">
        <div class="bg-white/5 backdrop-blur-xl border border-cyan-400/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-cyan-400/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-calendar-check text-cyan-400 text-[8px]"></i>
            </div>
            <p id="statAppointments" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Appointments</p>
        </div>
        <div class="bg-white/5 backdrop-blur-xl border border-vital-orange/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-vital-orange/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-pills text-vital-orange text-[8px]"></i>
            </div>
            <p id="statRefills" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Med Refills</p>
        </div>
        <div class="bg-white/5 backdrop-blur-xl border border-purple-400/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-purple-400/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-flask text-purple-400 text-[8px]"></i>
            </div>
            <p id="statLabTests" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Lab Tests</p>
        </div>
        <div class="bg-white/5 backdrop-blur-xl border border-green-400/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-green-400/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-user-doctor text-green-400 text-[8px]"></i>
            </div>
            <p id="statFollowups" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Follow-ups</p>
        </div>
        <div class="bg-white/5 backdrop-blur-xl border border-amber-400/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-amber-400/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-syringe text-amber-400 text-[8px]"></i>
            </div>
            <p id="statVaccinations" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Vaccinations</p>
        </div>
        <div class="bg-white/5 backdrop-blur-xl border border-pink-400/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-pink-400/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-shield-heart text-pink-400 text-[8px]"></i>
            </div>
            <p id="statInsurance" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Insurance</p>
        </div>
        <div class="bg-white/5 backdrop-blur-xl border border-red-400/20 rounded-md p-1.5 text-center">
            <div class="w-5 h-5 bg-red-400/20 rounded flex items-center justify-center mx-auto mb-0.5">
                <i class="fas fa-file-invoice-dollar text-red-400 text-[8px]"></i>
            </div>
            <p id="statBilling" class="text-sm font-bold text-white">0</p>
            <p class="text-white/50 text-[8px]">Bills Due</p>
        </div>
    </div>
</div>

<script>
// Calendar State
let currentDate = new Date();
let selectedDate = new Date();
let calendarEvents = [];

// Event Types Configuration
const eventTypes = {
    appointment: { color: 'bg-cyan-400', icon: 'fa-calendar-check', label: 'Appointment' },
    medication: { color: 'bg-vital-orange', icon: 'fa-pills', label: 'Medication Refill' },
    lab: { color: 'bg-purple-400', icon: 'fa-flask', label: 'Lab Test' },
    followup: { color: 'bg-green-400', icon: 'fa-user-doctor', label: 'Follow-up' },
    vaccination: { color: 'bg-amber-400', icon: 'fa-syringe', label: 'Vaccination' },
    insurance: { color: 'bg-pink-400', icon: 'fa-shield-heart', label: 'Insurance' },
    billing: { color: 'bg-red-400', icon: 'fa-file-invoice-dollar', label: 'Billing Due' }
};

// Initialize Calendar
function initCalendar() {
    loadCalendarEvents();
    renderCalendar();
    selectDate(new Date());
}

// Load calendar events from API
async function loadCalendarEvents() {
    try {
        const token = localStorage.getItem('patient_token') || localStorage.getItem('client_token');

        // For demo purposes, generate sample events
        // In production, this would fetch from the API
        calendarEvents = generateSampleEvents();

        renderCalendar();
        updateUpcomingEvents();
        updateMonthStats();

    } catch (error) {
        console.error('Error loading calendar events:', error);
        // Use sample data as fallback
        calendarEvents = generateSampleEvents();
        renderCalendar();
        updateUpcomingEvents();
        updateMonthStats();
    }
}

// Generate sample events for demo
function generateSampleEvents() {
    const today = new Date();
    const events = [];

    // Upcoming appointments
    events.push({
        id: 1,
        type: 'appointment',
        title: 'Annual Checkup',
        description: 'Dr. Sarah Johnson',
        date: addDays(today, 1),
        time: '10:00 AM'
    });

    events.push({
        id: 2,
        type: 'appointment',
        title: 'Dental Cleaning',
        description: 'Dr. Michael Chen',
        date: addDays(today, 5),
        time: '2:00 PM'
    });

    events.push({
        id: 3,
        type: 'followup',
        title: 'Follow-up Consultation',
        description: 'Dr. Emily Davis',
        date: addDays(today, 8),
        time: '11:30 AM'
    });

    // Medication refills
    events.push({
        id: 4,
        type: 'medication',
        title: 'Refill: Lisinopril',
        description: 'Blood pressure medication',
        date: addDays(today, 3),
        time: 'Due'
    });

    events.push({
        id: 5,
        type: 'medication',
        title: 'Refill: Metformin',
        description: 'Diabetes medication',
        date: addDays(today, 12),
        time: 'Due'
    });

    // Lab tests
    events.push({
        id: 6,
        type: 'lab',
        title: 'Blood Work',
        description: 'Comprehensive metabolic panel',
        date: addDays(today, 7),
        time: '8:00 AM'
    });

    events.push({
        id: 7,
        type: 'lab',
        title: 'Cholesterol Check',
        description: 'Lipid panel',
        date: addDays(today, 14),
        time: '9:00 AM'
    });

    // Vaccination
    events.push({
        id: 8,
        type: 'vaccination',
        title: 'Flu Shot',
        description: 'Annual flu vaccination',
        date: addDays(today, 10),
        time: '3:00 PM'
    });

    // Insurance
    events.push({
        id: 9,
        type: 'insurance',
        title: 'Policy Renewal',
        description: 'Annual insurance renewal due',
        date: addDays(today, 20),
        time: 'Due'
    });

    // Billing
    events.push({
        id: 10,
        type: 'billing',
        title: 'Invoice Payment',
        description: 'Lab services - $150.00',
        date: addDays(today, 4),
        time: 'Due'
    });

    // Past events
    events.push({
        id: 11,
        type: 'appointment',
        title: 'Eye Exam',
        description: 'Dr. Williams',
        date: addDays(today, -5),
        time: '11:00 AM'
    });

    events.push({
        id: 12,
        type: 'lab',
        title: 'Urinalysis',
        description: 'Routine check',
        date: addDays(today, -10),
        time: '10:00 AM'
    });

    return events;
}

// Helper function to add days
function addDays(date, days) {
    const result = new Date(date);
    result.setDate(result.getDate() + days);
    return result;
}

// Render the calendar grid
function renderCalendar() {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();

    // Update header
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                        'July', 'August', 'September', 'October', 'November', 'December'];
    document.getElementById('calendarMonthYear').textContent = `${monthNames[month]} ${year}`;

    // Get first day of month and total days
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const daysInPrevMonth = new Date(year, month, 0).getDate();

    const grid = document.getElementById('calendarGrid');
    grid.innerHTML = '';

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Previous month days
    for (let i = firstDay - 1; i >= 0; i--) {
        const day = daysInPrevMonth - i;
        const dateObj = new Date(year, month - 1, day);
        grid.appendChild(createDayCell(day, dateObj, true));
    }

    // Current month days
    for (let day = 1; day <= daysInMonth; day++) {
        const dateObj = new Date(year, month, day);
        const isToday = dateObj.getTime() === today.getTime();
        const isSelected = dateObj.toDateString() === selectedDate.toDateString();
        grid.appendChild(createDayCell(day, dateObj, false, isToday, isSelected));
    }

    // Next month days
    const totalCells = Math.ceil((firstDay + daysInMonth) / 7) * 7;
    const remainingCells = totalCells - (firstDay + daysInMonth);
    for (let day = 1; day <= remainingCells; day++) {
        const dateObj = new Date(year, month + 1, day);
        grid.appendChild(createDayCell(day, dateObj, true));
    }
}

// Create a day cell
function createDayCell(day, dateObj, isOtherMonth, isToday = false, isSelected = false) {
    const cell = document.createElement('div');
    const dayEvents = getEventsForDate(dateObj);

    let classes = 'relative min-h-[40px] p-1 rounded border transition-all duration-300 cursor-pointer ';

    if (isOtherMonth) {
        classes += 'bg-white/5 border-white/5 opacity-50 hover:opacity-75 ';
    } else if (isSelected) {
        classes += 'bg-cyan-400/20 border-cyan-400 ring-1 ring-cyan-400/50 ';
    } else if (isToday) {
        classes += 'bg-vital-orange/20 border-vital-orange ';
    } else {
        classes += 'bg-white/5 border-white/10 hover:bg-cyan-400/10 hover:border-cyan-400/30 ';
    }

    cell.className = classes;
    cell.onclick = () => selectDate(dateObj);

    // Day number
    let dayClass = 'text-[10px] font-semibold ';
    if (isToday) {
        dayClass += 'text-vital-orange';
    } else if (isSelected) {
        dayClass += 'text-cyan-400';
    } else if (isOtherMonth) {
        dayClass += 'text-white/30';
    } else {
        dayClass += 'text-white';
    }

    cell.innerHTML = `
        <span class="${dayClass}">${day}</span>
        <div class="flex flex-wrap gap-px mt-px">
            ${dayEvents.slice(0, 3).map(event => `
                <span class="w-1 h-1 rounded-full ${eventTypes[event.type].color}" title="${event.title}"></span>
            `).join('')}
            ${dayEvents.length > 3 ? `<span class="text-[7px] text-white/50">+${dayEvents.length - 3}</span>` : ''}
        </div>
    `;

    return cell;
}

// Get events for a specific date
function getEventsForDate(date) {
    return calendarEvents.filter(event => {
        const eventDate = new Date(event.date);
        return eventDate.toDateString() === date.toDateString();
    });
}

// Select a date
function selectDate(date) {
    selectedDate = date;
    renderCalendar();
    showEventsForDate(date);
}

// Show events for selected date
function showEventsForDate(date) {
    const events = getEventsForDate(date);
    const container = document.getElementById('selectedDateEvents');
    const title = document.getElementById('selectedDateTitle');

    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const isToday = date.toDateString() === today.toDateString();
    const dateStr = date.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' });

    title.innerHTML = `
        <i class="fas fa-calendar-check text-cyan-400 text-[10px]"></i>
        <span>${isToday ? "Today's Events" : dateStr}</span>
    `;

    if (events.length === 0) {
        container.innerHTML = `
            <div class="text-center py-3">
                <i class="fas fa-calendar-xmark text-white/20 text-lg mb-1"></i>
                <p class="text-white/50 text-[9px]">No events scheduled</p>
            </div>
        `;
        return;
    }

    container.innerHTML = events.map(event => `
        <div class="p-1.5 bg-white/5 rounded border border-white/10 hover:border-cyan-400/30 transition-all duration-300 hover:bg-white/10">
            <div class="flex items-start gap-1.5">
                <div class="w-5 h-5 ${eventTypes[event.type].color} rounded flex items-center justify-center flex-shrink-0">
                    <i class="fas ${eventTypes[event.type].icon} text-white text-[8px]"></i>
                </div>
                <div class="flex-1 min-w-0">
                    <p class="text-white font-semibold text-[10px] truncate">${event.title}</p>
                    <p class="text-white/50 text-[9px] truncate">${event.description}</p>
                    <p class="text-cyan-400 text-[9px] mt-px">
                        <i class="fas fa-clock mr-0.5"></i>${event.time}
                    </p>
                </div>
            </div>
        </div>
    `).join('');
}

// Update upcoming events list
function updateUpcomingEvents() {
    const container = document.getElementById('upcomingEventsList');
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const upcoming = calendarEvents
        .filter(event => new Date(event.date) >= today)
        .sort((a, b) => new Date(a.date) - new Date(b.date))
        .slice(0, 10);

    if (upcoming.length === 0) {
        container.innerHTML = `
            <div class="text-center py-3">
                <i class="fas fa-calendar-check text-white/20 text-lg mb-1"></i>
                <p class="text-white/50 text-[9px]">No upcoming events</p>
            </div>
        `;
        return;
    }

    container.innerHTML = upcoming.map(event => {
        const eventDate = new Date(event.date);
        const dateStr = eventDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        const isToday = eventDate.toDateString() === today.toDateString();

        return `
            <div class="p-1.5 bg-white/5 rounded border border-white/10 hover:border-cyan-400/30 transition-all duration-300 cursor-pointer" onclick="selectDate(new Date('${eventDate.toISOString()}'))">
                <div class="flex items-start gap-1.5">
                    <div class="w-5 h-5 ${eventTypes[event.type].color} rounded flex items-center justify-center flex-shrink-0">
                        <i class="fas ${eventTypes[event.type].icon} text-white text-[8px]"></i>
                    </div>
                    <div class="flex-1 min-w-0">
                        <p class="text-white font-semibold text-[10px] truncate">${event.title}</p>
                        <p class="text-white/50 text-[9px]">${event.description}</p>
                        <div class="flex items-center gap-1 mt-px">
                            <span class="${isToday ? 'text-vital-orange' : 'text-cyan-400'} text-[9px]">
                                <i class="fas fa-calendar-day mr-0.5"></i>${isToday ? 'Today' : dateStr}
                            </span>
                            <span class="text-white/40 text-[9px]">•</span>
                            <span class="text-white/50 text-[9px]">${event.time}</span>
                        </div>
                    </div>
                </div>
            </div>
        `;
    }).join('');
}

// Update month statistics
function updateMonthStats() {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();

    const monthEvents = calendarEvents.filter(event => {
        const eventDate = new Date(event.date);
        return eventDate.getFullYear() === year && eventDate.getMonth() === month;
    });

    const stats = {
        appointment: 0,
        medication: 0,
        lab: 0,
        followup: 0,
        vaccination: 0,
        insurance: 0,
        billing: 0
    };

    monthEvents.forEach(event => {
        if (stats.hasOwnProperty(event.type)) {
            stats[event.type]++;
        }
    });

    document.getElementById('statAppointments').textContent = stats.appointment;
    document.getElementById('statRefills').textContent = stats.medication;
    document.getElementById('statLabTests').textContent = stats.lab;
    document.getElementById('statFollowups').textContent = stats.followup;
    document.getElementById('statVaccinations').textContent = stats.vaccination;
    document.getElementById('statInsurance').textContent = stats.insurance;
    document.getElementById('statBilling').textContent = stats.billing;
}

// Change month
function changeMonth(delta) {
    currentDate.setMonth(currentDate.getMonth() + delta);
    renderCalendar();
    updateMonthStats();
}

// Go to today
function goToToday() {
    currentDate = new Date();
    selectedDate = new Date();
    renderCalendar();
    showEventsForDate(selectedDate);
    updateMonthStats();
}

// Initialize on page load if calendar section is visible
document.addEventListener('DOMContentLoaded', function() {
    // Calendar will be initialized when section is shown
});
</script>

